# Generated by Django 4.2.7 on 2024-06-19 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_reg', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BgImages',
        ),
    ]
